- name: Create an EDA Credential - GitHub
  ansible.eda.credential:
    controller_host: "{{ eda_controller_url }}"
    controller_username: "{{ eda_controller_user }}"
    controller_password: "{{ eda_controller_password }}"
    name: "{{ item.name }}"
    inputs:
      username: "{{ item.username }}"
      password: "{{ item.secret }}"
    credential_type_name: "{{ item.credential_type }}"
    organization_name: "{{ item.organization | default('Default', true) }}"
    state: present
  loop: "{{ eda_credentials_github }}"