- name: Create EDA Projects
  ansible.eda.project:
    controller_host: "{{ eda_controller_url }}"
    controller_username: "{{ eda_controller_username }}"
    controller_password: "{{ eda_controller_password }}"
    validate_certs: false
    name: "{{ item.name }}"
    url: "{{ item.git_url }}"
    credential: "{{ item.credential | default(omit, true) }}"
    organization_name: "{{ item.organization | default('Default', true) }}"
    description: "{{ item.description | default(omit, true) }}"
    state: present
  loop: "{{ eda_projects }}"

