- name: Create EDA Decision Environment
  ansible.eda.decision_environment:
    controller_host: "{{ eda_controller_url }}"
    controller_username: "{{ eda_controller_username }}"
    controller_password: "{{ eda_controller_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    image_url: "{{ item.image_url }}"
    credential: "{{ item.credential | default(omit, true) }}"
    organization_name: "{{ item.organization | default('Default', true) }}"
    state: present
  loop: "{{ eda_decision_envs }}"