- name: Create EDA Projects
  ansible.eda.project:
    controller_host: "{{ eda_controller_url }}"
    controller_username: "{{ eda_controller_user }}"
    controller_password: "{{ eda_controller_password }}"
    name: "{{ item.name }}"
    url: "{{ item.git_url }}"
    credential: "{{ item.credential }}"
    organization_name: "{{ item.organization | default('Default', true) }}"
    description: "{{ item.description }}"
    state: present
  loop: "{{ eda_projects }}"

